-- 1-5. 집합 연산자
-- 두개 이상의 SELECT절 결과를 하나로 결합함. 
-- UNION / UNION ALL / INTERSECT, EXCEPT

USE EDU
SELECT * FROM [MEMBER_1]
SELECT * FROM [MEMBER_2]

-- 합집합 row-bind 결합 
-- UNION (중복X) , UNION ALL(중복 O) 
SELECT * FROM [MEMBER_1]
UNION 
SELECT * FROM [MEMBER_2]

SELECT * FROM [MEMBER_1]
UNION ALL 
SELECT * FROM [MEMBER_2]



-- 교집합 row-bind 결합 
-- INTERSECT (중복X)
SELECT * FROM [MEMBER_1]
INTERSECT
SELECT * FROM [MEMBER_2] 


-- 차집합 row-bind 결합
-- EXCEPT (중복X)
SELECT * FROM [MEMBER_1]
EXCEPT 
SELECT * FROM [MEMBER_2] 

SELECT * FROM [MEMBER_2]
EXCEPT 
SELECT * FROM [MEMBER_1] 